name: gnome_wallpaper_slideshow
description: A simple command-line app that configures a wallpaper slideshow in GNOME environment.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  xml: ^5.1.0

dev_dependencies:
  pedantic: ^1.9.0
